name: 'build-test'
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: philipssoftware/sonar-scanner:4.3

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Build distribution
        run: yarn build
